// Source of truth for the settings search/registry; settings-registry.ts interprets it at runtime.

import {
  DEFAULT_BATCH_CONCURRENCY,
  DEFAULT_CONFIDENCE_PILL_THRESHOLD,
  DEFAULT_DESCRIPTION_CONTEXT_CAP,
  DEFAULT_HEADING_TRAIL_DEPTH,
  DEFAULT_HEADING_TRAIL_ENTRY_CAP,
  DEFAULT_IMAGE_TRANSLATE_TIMEOUT_MS,
  DEFAULT_LOCAL_BACKEND_TIMEOUT_MS,
  DEFAULT_POST_TEXT_CAP,
  DEFAULT_SELECTION_CONTEXT_CAP,
  DEFAULT_SMART_BUBBLE_MIN_LENGTH,
  DEFAULT_STREAMING_FLUSH_MS,
  DEFAULT_TRANSLATE_TIMEOUT_MS,
} from './constants';
import { DEFAULT_SETTINGS } from './settings-defaults';
import { DEFAULT_TEMPLATE } from './prompts';
import type { SettingsTab } from './settings-tabs';
import type { Settings } from './types';

export type { SettingsTab };

/** `action` is a button that does something once (reset, clear, delete), not a value. */
export type SettingType = 'toggle' | 'slider' | 'select' | 'text' | 'template' | 'group' | 'action';

export type AdvancedSubTab = 'diagnostics' | 'data' | 'labs';

/** `fallback` is the shipped default the stored value is compared against by value.
 *  `custom.paths` lists what `fn` reads — the coverage gate cannot see inside it. */
export type IsModifiedSpec =
  | { kind: 'eq'; path: string }
  | { kind: 'fallback'; path: string; fallback: number }
  | { kind: 'nonEmpty'; path: string }
  | { kind: 'jsonStringify'; path: string }
  | { kind: 'custom'; paths: readonly string[]; fn: (s: Settings) => boolean };

export interface SettingEntrySpec {
  readonly id: string;
  readonly label: string;
  readonly description: string;
  readonly keywords: readonly string[];
  readonly tab: SettingsTab;
  readonly subTab?: AdvancedSubTab;
  readonly targetSelector?: string;
  readonly type: SettingType;
  readonly defaultValue?: string;
  readonly isModified?: IsModifiedSpec;
}

export const SETTINGS_SPEC: readonly SettingEntrySpec[] = [
  // ── Display ──────────────────────────────────────────────────────
  {
    id: 'display.bubbleMode',
    label: 'Selection bubble',
    description:
      'Smart hides the bubble on short selections and on English text. Always shows it on every selection. Never turns the bubble off.',
    keywords: ['bubble', 'selection', 'smart', 'always', 'never', 'popup', 'show'],
    tab: 'selection-bubble',
    type: 'select',
    isModified: { kind: 'eq', path: 'bubbleMode' },
  },
  {
    id: 'display.pickerEnabled',
    label: 'Element picker',
    description: 'Hover to outline an element, click to translate it, Esc to cancel.',
    keywords: ['picker', 'element', 'click', 'pick', 'hover'],
    tab: 'selection-bubble',
    targetSelector: '[data-ega-setting="display.pickerEnabled"]',
    type: 'toggle',
    isModified: { kind: 'eq', path: 'pickerEnabled' },
  },
  {
    id: 'display.pickerShortcut',
    label: 'Element picker shortcut',
    description: 'Keyboard shortcut that starts the element picker.',
    keywords: ['picker', 'shortcut', 'keybinding', 'hotkey'],
    tab: 'selection-bubble',
    targetSelector: '[data-ega-setting="display.pickerShortcut"]',
    type: 'text',
    isModified: { kind: 'eq', path: 'pickerShortcut' },
  },
  {
    id: 'display.shortcut',
    label: 'In-page translate shortcut',
    description: 'Keyboard shortcut that translates the selection on a web page.',
    keywords: ['shortcut', 'keybinding', 'hotkey', 'translate', 'key'],
    tab: 'selection-bubble',
    targetSelector: '[data-ega-setting="display.shortcut"]',
    type: 'text',
    isModified: { kind: 'eq', path: 'shortcut' },
  },
  {
    id: 'display.theme',
    label: 'Theme',
    description: 'Light, dark, or system color scheme. Toggle from the Settings header.',
    keywords: ['dark', 'light', 'colour', 'color', 'mode', 'theme'],
    tab: 'about',
    type: 'select',
    isModified: { kind: 'eq', path: 'theme' },
  },
  {
    id: 'display.defaultDisplayMode',
    label: 'Default display mode',
    description: 'Tooltip overlay vs inline replacement for translation results.',
    keywords: ['tooltip', 'inline', 'surface', 'display', 'mode'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="display.defaultDisplayMode"]',
    type: 'select',
    isModified: { kind: 'eq', path: 'defaultDisplayMode' },
  },
  {
    id: 'display.imageTranslateSurface',
    label: 'Image translation surface',
    description: 'Where image translation results appear — side panel or tooltip.',
    keywords: ['image', 'ocr', 'sidepanel', 'tooltip', 'surface'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="display.imageTranslateSurface"]',
    type: 'select',
    isModified: { kind: 'eq', path: 'imageTranslateSurface' },
  },
  {
    id: 'display.streaming',
    label: 'Streaming responses',
    description: 'Show the text as the model writes it, instead of waiting for the whole reply.',
    keywords: ['streaming', 'stream', 'token', 'live'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="display.streaming"]',
    type: 'toggle',
    isModified: { kind: 'eq', path: 'streaming' },
  },
  {
    id: 'display.streamingFlushMs',
    label: 'Streaming flush speed',
    description:
      'How often streamed text is drawn. 0 = instant, about 50 ms is smooth, and above about 100 ms streaming starts to look frozen.',
    keywords: ['streaming', 'flush', 'paint', 'render', 'speed'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="display.streamingFlushMs"]',
    type: 'slider',
    isModified: {
      kind: 'fallback',
      path: 'streamingFlushMs',
      fallback: DEFAULT_STREAMING_FLUSH_MS,
    },
  },
  {
    id: 'display.confidencePill',
    label: 'Confidence pill',
    description: 'Show a confidence badge next to translations.',
    keywords: ['confidence', 'pill', 'badge', 'score'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="display.confidencePill"]',
    type: 'toggle',
    isModified: { kind: 'eq', path: 'confidencePill' },
  },
  {
    id: 'display.confidencePillThreshold',
    label: 'Confidence pill threshold',
    description: 'Hide the pill below this confidence score; 0 = always show.',
    keywords: ['confidence', 'threshold', 'score'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="display.confidencePillThreshold"]',
    type: 'slider',
    // (s.confidencePillThreshold ?? DEFAULT) !== DEFAULT collapses to "value set and not the default"
    isModified: {
      kind: 'fallback',
      path: 'confidencePillThreshold',
      fallback: DEFAULT_CONFIDENCE_PILL_THRESHOLD,
    },
  },
  {
    id: 'display.tooltipShowSource',
    label: 'Show source in tooltip',
    description: 'Show the original selection at the top of the tooltip.',
    keywords: ['source', 'original', 'tooltip', 'echo'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="display.tooltipShowSource"]',
    type: 'toggle',
    isModified: { kind: 'eq', path: 'tooltipShowSource' },
  },
  {
    id: 'display.tooltipClickOutside',
    label: 'Click outside to dismiss tooltip',
    description: 'Click anywhere off the tooltip to dismiss; hides the close button.',
    keywords: ['click', 'outside', 'dismiss', 'tooltip', 'close'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="display.tooltipClickOutside"]',
    type: 'toggle',
    isModified: { kind: 'eq', path: 'tooltipClickOutside' },
  },
  {
    id: 'display.tooltipDraggable',
    label: 'Drag-to-move tooltip',
    description: "Drag from the narrow handle on the tooltip's left edge to move it.",
    keywords: ['drag', 'tooltip', 'move', 'reposition'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="display.tooltipDraggable"]',
    type: 'toggle',
    isModified: { kind: 'eq', path: 'tooltipDraggable' },
  },
  {
    id: 'display.contextEnabled',
    label: 'Send page context',
    description:
      'Send the page title, address and nearby text with selection and side panel requests.',
    keywords: ['context', 'page', 'metadata', 'surrounding'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="display.contextEnabled"]',
    type: 'toggle',
    isModified: { kind: 'eq', path: 'contextEnabled' },
  },
  {
    id: 'display.explainUsesPageImage',
    label: 'Explain can read the page image',
    description:
      "When Explain runs on selected text, send the page's one dominant image so the model can read it.",
    keywords: ['explain', 'image', 'picture', 'vision', 'post', 'meme'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="display.explainUsesPageImage"]',
    type: 'toggle',
    isModified: { kind: 'eq', path: 'explainUsesPageImage' },
  },
  {
    id: 'display.pageContextLevel',
    label: 'Page-context depth',
    description: `Minimal sends the title, URL and the text around the selection. Rich adds the page language, headings, the page description and the site name, and, on a selection, up to ${DEFAULT_POST_TEXT_CAP} characters of the post around it.`,
    keywords: ['context', 'depth', 'level', 'minimal', 'rich', 'page'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="display.pageContextLevel"]',
    type: 'select',
    defaultValue: DEFAULT_SETTINGS.pageContextLevel,
    isModified: { kind: 'eq', path: 'pageContextLevel' },
  },
  {
    id: 'display.pageTranslateMode',
    label: 'Page-translate render mode',
    description:
      'In place replaces the block text. Bilingual keeps the original and adds the translation below it.',
    keywords: ['page', 'translate', 'inplace', 'bilingual', 'render', 'mode', 'side by side'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="display.pageTranslateMode"]',
    type: 'select',
    defaultValue: DEFAULT_SETTINGS.pageTranslateMode,
    isModified: { kind: 'eq', path: 'pageTranslateMode' },
  },
  // ── Defaults ─────────────────────────────────────────────────────
  {
    id: 'defaults.defaultLang',
    label: 'Default source language',
    description:
      'Source language for new translations. Auto-detect tries on your device first, then asks the backend.',
    keywords: ['source', 'language', 'auto', 'detect', 'default'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="defaults.defaultLang"]',
    type: 'select',
    isModified: { kind: 'eq', path: 'defaultLang' },
  },
  {
    id: 'defaults.defaultTargetLang',
    label: 'Default target language',
    description: 'The language Ega translates into.',
    keywords: ['target', 'language', 'destination', 'default'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="defaults.defaultTargetLang"]',
    type: 'select',
    isModified: { kind: 'eq', path: 'defaultTargetLang' },
  },
  {
    id: 'defaults.defaultTask',
    label: 'Default task',
    description: 'Translate, Explain, Summarize, Reword, Grammar, Reply ideas or Ask.',
    keywords: ['task', 'translate', 'explain', 'summarize', 'reword', 'grammar', 'default'],
    tab: 'tasks',
    targetSelector: '[data-ega-setting="defaults.defaultTask"]',
    type: 'select',
    isModified: { kind: 'eq', path: 'defaultTask' },
  },
  {
    id: 'defaults.defaultTone',
    label: 'Default tone',
    description:
      'The tone a task uses unless you pick another, e.g. formal or casual. Only tasks that write in a tone use it, like Reword.',
    keywords: ['tone', 'reword', 'formal', 'casual', 'voice'],
    tab: 'tasks',
    targetSelector: '[data-ega-setting="defaults.defaultTone"]',
    type: 'select',
    isModified: { kind: 'eq', path: 'defaultTone' },
  },
  {
    id: 'tasks.enabled',
    label: 'Tasks on and off',
    description:
      'Turn a task off to hide it in the side panel, tooltip, Re-run, palette and right-click menu.',
    keywords: ['task', 'off', 'hide', 'disable', 'picker'],
    tab: 'tasks',
    targetSelector: '[data-ega-setting="tasks.enabled"]',
    type: 'group',
    isModified: { kind: 'nonEmpty', path: 'disabledTasks' },
  },
  {
    id: 'tasks.overrides',
    label: 'Task settings',
    description: 'Per task: effort, page context and glossary.',
    keywords: ['task', 'effort', 'page context', 'glossary', 'reset'],
    tab: 'tasks',
    targetSelector: '[data-ega-setting="tasks.overrides"]',
    type: 'group',
    isModified: { kind: 'nonEmpty', path: 'taskOverrides' },
  },
  {
    id: 'tasks.backupRestore',
    label: 'Backup & restore tasks',
    description: 'Export your tasks, task edits and on/off state, or import from JSON.',
    keywords: ['backup', 'restore', 'export', 'import', 'json', 'task'],
    tab: 'tasks',
    type: 'group',
  },

  // ── Backends ─────────────────────────────────────────────────────
  {
    id: 'backends.backendOrder',
    label: 'Backend order',
    description: 'The order Ega tries backends in. Drag to reorder.',
    keywords: ['backend', 'order', 'priority', 'fallback', 'chain', 'drag'],
    tab: 'backends',
    type: 'group',
    isModified: { kind: 'jsonStringify', path: 'backendOrder' },
  },
  {
    id: 'backends.disabledBackends',
    label: 'Disabled backends',
    description: 'Backends Ega never tries, even when they are set up.',
    keywords: ['disabled', 'backend', 'exclude', 'off'],
    tab: 'backends',
    type: 'group',
    // The default list is non-empty, so compare contents, not emptiness.
    isModified: { kind: 'jsonStringify', path: 'disabledBackends' },
  },
  {
    id: 'backends.model',
    label: 'Model per backend',
    description: 'Which model id each backend calls. Set from the model box on the backend card.',
    keywords: ['model', 'id', 'gpt', 'claude', 'gemini', 'llama', 'pick', 'choose'],
    tab: 'backends',
    targetSelector: '[data-ega-model-combobox]',
    type: 'select',
    isModified: { kind: 'jsonStringify', path: 'model' },
  },
  {
    id: 'backends.anthropicApiKey',
    label: 'Anthropic API key',
    description: 'Claude (Anthropic) authentication.',
    keywords: ['anthropic', 'claude', 'api', 'key', 'auth', 'cloud'],
    tab: 'backends',
    type: 'text',
    isModified: { kind: 'nonEmpty', path: 'anthropicApiKey' },
  },
  {
    id: 'backends.openaiApiKey',
    label: 'OpenAI API key',
    description: 'GPT (OpenAI) authentication.',
    keywords: ['openai', 'gpt', 'api', 'key', 'auth', 'cloud'],
    tab: 'backends',
    type: 'text',
    isModified: { kind: 'nonEmpty', path: 'openaiApiKey' },
  },
  {
    id: 'backends.geminiApiKey',
    label: 'Gemini API key',
    description: 'Google Gemini authentication.',
    keywords: ['gemini', 'google', 'api', 'key', 'auth', 'cloud'],
    tab: 'backends',
    type: 'text',
    isModified: { kind: 'nonEmpty', path: 'geminiApiKey' },
  },
  {
    id: 'backends.groqApiKey',
    label: 'Groq API key',
    description: 'Groq cloud authentication.',
    keywords: ['groq', 'api', 'key', 'auth', 'cloud'],
    tab: 'backends',
    type: 'text',
    isModified: { kind: 'nonEmpty', path: 'groqApiKey' },
  },
  {
    id: 'backends.deepseekApiKey',
    label: 'DeepSeek API key',
    description: 'DeepSeek cloud authentication.',
    keywords: ['deepseek', 'api', 'key', 'auth', 'cloud'],
    tab: 'backends',
    type: 'text',
    isModified: { kind: 'nonEmpty', path: 'deepseekApiKey' },
  },
  {
    id: 'backends.togetherApiKey',
    label: 'Together API key',
    description: 'Together AI cloud authentication.',
    keywords: ['together', 'api', 'key', 'auth', 'cloud'],
    tab: 'backends',
    type: 'text',
    isModified: { kind: 'nonEmpty', path: 'togetherApiKey' },
  },
  {
    id: 'backends.mistralApiKey',
    label: 'Mistral API key',
    description: 'Mistral cloud authentication.',
    keywords: ['mistral', 'api', 'key', 'auth', 'cloud'],
    tab: 'backends',
    type: 'text',
    isModified: { kind: 'nonEmpty', path: 'mistralApiKey' },
  },
  {
    id: 'backends.xaiApiKey',
    label: 'xAI API key',
    description: 'xAI (Grok) cloud authentication.',
    keywords: ['xai', 'grok', 'api', 'key', 'auth', 'cloud'],
    tab: 'backends',
    type: 'text',
    isModified: { kind: 'nonEmpty', path: 'xaiApiKey' },
  },
  {
    id: 'backends.fireworksApiKey',
    label: 'Fireworks API key',
    description: 'Fireworks AI cloud authentication.',
    keywords: ['fireworks', 'api', 'key', 'auth', 'cloud'],
    tab: 'backends',
    type: 'text',
    isModified: { kind: 'nonEmpty', path: 'fireworksApiKey' },
  },
  {
    id: 'backends.openrouterApiKey',
    label: 'OpenRouter API key',
    description: 'OpenRouter cloud authentication.',
    keywords: ['openrouter', 'api', 'key', 'auth', 'cloud'],
    tab: 'backends',
    type: 'text',
    isModified: { kind: 'nonEmpty', path: 'openrouterApiKey' },
  },
  {
    id: 'backends.ollamaUrl',
    label: 'Ollama URL',
    description: 'Address of your local Ollama server. Default http://localhost:11434.',
    keywords: ['ollama', 'local', 'url', 'endpoint', 'daemon'],
    tab: 'backends',
    type: 'text',
    // Nullable string compared with nullable default — collapse both sides via ?? ''.
    isModified: {
      kind: 'custom',
      paths: ['ollamaUrl'],
      fn: (s) => (s.ollamaUrl ?? '') !== (DEFAULT_SETTINGS.ollamaUrl ?? ''),
    },
  },
  {
    id: 'backends.localServerUrl',
    label: 'Local server URL',
    description:
      'Address of LM Studio, llama-server or another OpenAI-compatible server on this computer. Default http://127.0.0.1:1234 (LM Studio); llama-server uses port 8080.',
    keywords: [
      'local',
      'server',
      'url',
      'lm studio',
      'lmstudio',
      'llama.cpp',
      'llama-server',
      'openai',
    ],
    tab: 'backends',
    type: 'text',
    isModified: {
      kind: 'custom',
      paths: ['localServerUrl'],
      fn: (s) => (s.localServerUrl ?? '') !== (DEFAULT_SETTINGS.localServerUrl ?? ''),
    },
  },
  {
    id: 'backends.nativeCli',
    label: 'Native host CLI',
    description: 'Which CLI the native host runs: Claude Code or Codex.',
    keywords: ['native', 'host', 'claude', 'codex', 'cli'],
    tab: 'backends',
    type: 'select',
    isModified: { kind: 'eq', path: 'nativeCli' },
  },
  {
    id: 'backends.localBackendTimeoutMs',
    label: 'Local-backend check timeout',
    description: 'How long Ega waits when checking that a local backend is reachable.',
    keywords: ['local', 'native', 'ollama', 'server', 'timeout', 'check', 'reachable'],
    tab: 'backends',
    type: 'slider',
    isModified: {
      kind: 'fallback',
      path: 'localBackendTimeoutMs',
      fallback: DEFAULT_LOCAL_BACKEND_TIMEOUT_MS,
    },
  },
  {
    id: 'backends.preWarmNative',
    label: 'Start the native CLI with the browser',
    description:
      'Starts the claude CLI when the browser starts, so the first translation skips a 7-12 s warm-up. The codex CLI runs one process per translation, so it does not start early. Off saves battery on machines that rarely translate.',
    keywords: ['pre-warm', 'prewarm', 'warm', 'native', 'cold', 'start', 'boot', 'spawn'],
    tab: 'backends',
    targetSelector: '[data-ega-setting="backends.preWarmNative"]',
    type: 'toggle',
    // Default is `true` → "modified" means user disabled it.
    isModified: { kind: 'custom', paths: ['preWarmNative'], fn: (s) => s.preWarmNative === false },
  },
  // ── Languages ────────────────────────────────────────────────────
  {
    id: 'languages.varieties',
    label: 'Language varieties',
    description: 'Built-in and custom languages, with detection rules and translation examples.',
    keywords: ['variety', 'dialect', 'language', 'custom'],
    tab: 'languages',
    type: 'group',
  },
  {
    id: 'languages.disabledVarieties',
    label: 'Disabled languages',
    description: 'Languages hidden from the language menus and skipped by auto-detect.',
    keywords: ['disabled', 'variety', 'off', 'skip'],
    tab: 'languages',
    type: 'group',
    isModified: { kind: 'nonEmpty', path: 'disabledVarieties' },
  },
  {
    id: 'languages.customLanguages',
    label: 'Custom languages',
    description: 'Languages you added yourself.',
    keywords: ['custom', 'variety', 'add', 'user'],
    tab: 'languages',
    type: 'group',
  },
  {
    id: 'languages.varietyOverrides',
    label: 'Built-in language edits',
    description: 'Your edits to built-in languages: hint, examples and detection rules.',
    keywords: ['override', 'variety', 'edit', 'hint', 'example'],
    tab: 'languages',
    type: 'group',
    isModified: { kind: 'nonEmpty', path: 'varietyOverrides' },
  },
  {
    id: 'languages.backupRestore',
    label: 'Backup & restore languages',
    description: 'Export your custom languages and overrides, or import from JSON.',
    keywords: ['backup', 'restore', 'export', 'import', 'json'],
    tab: 'languages',
    type: 'group',
  },

  // ── Advanced ─────────────────────────────────────────────────────
  {
    id: 'advanced.promptTemplate',
    label: 'Translate prompt',
    description: 'The prompt Translate, Explain and every language without its own prompt use.',
    keywords: ['template', 'prompt', 'system', 'user', 'slot', 'global'],
    tab: 'tasks',
    targetSelector: '[data-ega-task-item="translate"]',
    type: 'template',
    isModified: {
      kind: 'custom',
      paths: ['advanced.promptTemplate'],
      fn: (s) =>
        s.advanced.promptTemplate.system !== DEFAULT_TEMPLATE.system ||
        s.advanced.promptTemplate.user !== DEFAULT_TEMPLATE.user,
    },
  },
  {
    id: 'advanced.perPresetTemplates',
    label: 'Prompt for one language',
    description: 'Edit a language to give it its own prompt for Translate and Explain.',
    keywords: ['preset', 'template', 'override', 'per-preset', 'language', 'prompt'],
    tab: 'languages',
    type: 'template',
    isModified: { kind: 'nonEmpty', path: 'advanced.perPresetTemplates' },
  },
  {
    id: 'advanced.rules',
    label: 'Rules',
    description:
      'Rules Ega adds to the system prompt. A rule can be limited to some tasks or sites, or turned off.',
    keywords: ['rule', 'rules', 'always', 'never', 'prefer', 'format', 'declarative'],
    tab: 'tasks',
    targetSelector: '[data-ega-setting="tasks.rules"]',
    type: 'group',
    isModified: { kind: 'nonEmpty', path: 'advanced.rules' },
  },
  {
    id: 'advanced.temperature',
    label: 'Temperature (global)',
    description:
      '0 = most predictable, 2 = most varied. Default 0.2. Above about 1.2 the reply format can break, and 0 can make some backends repeat themselves.',
    keywords: ['creativity', 'random', 'heat', 'sampling', 'temperature'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="advanced.temperature"]',
    type: 'slider',
    defaultValue: String(DEFAULT_SETTINGS.advanced.temperature),
    // The 0.05 slider step lands on 0.30000000000000004, so a strict !== would flag the visible default.
    isModified: {
      kind: 'custom',
      paths: ['advanced.temperature'],
      fn: (s) => Math.abs(s.advanced.temperature - DEFAULT_SETTINGS.advanced.temperature) >= 1e-9,
    },
  },
  {
    id: 'advanced.maxTokens',
    label: 'Max answer length (tokens)',
    description:
      'Longest reply the model may write. Below 256 tokens, replies can be cut short and lose the confidence score and language detection.',
    keywords: ['length', 'output', 'tokens', 'max tokens', 'cap', 'max'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="advanced.maxTokens"]',
    type: 'slider',
    defaultValue: String(DEFAULT_SETTINGS.advanced.maxTokens),
    isModified: { kind: 'eq', path: 'advanced.maxTokens' },
  },
  {
    id: 'advanced.effort',
    label: 'Effort',
    description:
      'How much a model thinks before it answers: Off, Low, Medium or High. Ega maps it to each backend; models without a thinking setting ignore it.',
    keywords: [
      'reasoning',
      'thinking level',
      'gemini',
      'effort',
      'thinking',
      'openai',
      'o-series',
      'gpt-5',
      'gpt-6',
      'gpt-oss',
      'anthropic',
      'claude',
    ],
    tab: 'translate',
    targetSelector: '[data-ega-setting="advanced.effort"]',
    type: 'select',
    defaultValue: String(DEFAULT_SETTINGS.advanced.effort),
    isModified: { kind: 'eq', path: 'advanced.effort' },
  },
  {
    id: 'advanced.batchConcurrency',
    label: 'Batch concurrency',
    description: 'How many parts of the page translate at the same time.',
    keywords: ['concurrency', 'parallel', 'workers', 'batch', 'page-translate'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="advanced.batchConcurrency"]',
    type: 'slider',
    isModified: {
      kind: 'fallback',
      path: 'batchConcurrency',
      fallback: DEFAULT_BATCH_CONCURRENCY,
    },
  },
  {
    id: 'advanced.smartBubbleMinLength',
    label: 'Smart bubble minimum length',
    description: 'Below this length, smart mode hides the bubble.',
    keywords: ['smart', 'bubble', 'length', 'short', 'min'],
    tab: 'selection-bubble',
    targetSelector: '[data-ega-setting="advanced.smartBubbleMinLength"]',
    type: 'slider',
    isModified: {
      kind: 'fallback',
      path: 'smartBubbleMinLength',
      fallback: DEFAULT_SMART_BUBBLE_MIN_LENGTH,
    },
  },
  {
    id: 'advanced.pageContextPayload',
    label: 'Page-context payload caps',
    description: 'Limits for nearby text, the page description and headings.',
    keywords: ['context', 'payload', 'cap', 'page', 'heading', 'description'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="advanced.pageContextPayload"]',
    type: 'group',
    isModified: {
      kind: 'custom',
      paths: [
        'selectionContextCap',
        'descriptionContextCap',
        'headingTrailDepth',
        'headingTrailEntryCap',
      ],
      fn: (s) =>
        (s.selectionContextCap !== undefined &&
          s.selectionContextCap !== DEFAULT_SELECTION_CONTEXT_CAP) ||
        (s.descriptionContextCap !== undefined &&
          s.descriptionContextCap !== DEFAULT_DESCRIPTION_CONTEXT_CAP) ||
        (s.headingTrailDepth !== undefined &&
          s.headingTrailDepth !== DEFAULT_HEADING_TRAIL_DEPTH) ||
        (s.headingTrailEntryCap !== undefined &&
          s.headingTrailEntryCap !== DEFAULT_HEADING_TRAIL_ENTRY_CAP),
    },
  },
  {
    id: 'advanced.selectionContextCap',
    label: 'Selection window',
    description: 'How much text before and after the selection travels with the request.',
    keywords: ['selection', 'window', 'neighbourhood', 'cap', 'context', 'chars'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="advanced.selectionContextCap"]',
    type: 'slider',
    isModified: {
      kind: 'fallback',
      path: 'selectionContextCap',
      fallback: DEFAULT_SELECTION_CONTEXT_CAP,
    },
  },
  {
    id: 'advanced.descriptionContextCap',
    label: 'Page description length',
    description: 'Longest page description sent with Rich context.',
    keywords: ['description', 'meta', 'cap', 'context', 'chars', 'rich'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="advanced.descriptionContextCap"]',
    type: 'slider',
    isModified: {
      kind: 'fallback',
      path: 'descriptionContextCap',
      fallback: DEFAULT_DESCRIPTION_CONTEXT_CAP,
    },
  },
  {
    id: 'advanced.headingTrailDepth',
    label: 'Headings sent',
    description: 'How many nearby h1–h6 headings rich context carries.',
    keywords: ['heading', 'trail', 'depth', 'context', 'rich', 'h1'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="advanced.headingTrailDepth"]',
    type: 'slider',
    isModified: {
      kind: 'fallback',
      path: 'headingTrailDepth',
      fallback: DEFAULT_HEADING_TRAIL_DEPTH,
    },
  },
  {
    id: 'advanced.headingTrailEntryCap',
    label: 'Longest heading',
    description: 'Longest single heading in the trail.',
    keywords: ['heading', 'trail', 'cap', 'chars', 'context'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="advanced.headingTrailEntryCap"]',
    type: 'slider',
    isModified: {
      kind: 'fallback',
      path: 'headingTrailEntryCap',
      fallback: DEFAULT_HEADING_TRAIL_ENTRY_CAP,
    },
  },
  {
    id: 'advanced.retryCount',
    label: 'Fallback depth',
    description: 'How many more backends to try after the first one fails.',
    keywords: ['retry', 'fallback', 'chain', 'rate-limit', 'network', 'attempts'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="advanced.retryCount"]',
    type: 'slider',
    defaultValue: String(DEFAULT_SETTINGS.advanced.retryCount),
    isModified: { kind: 'eq', path: 'advanced.retryCount' },
  },
  {
    id: 'advanced.backendProbeTtlMs',
    label: 'Backend status memory',
    description: 'How long Ega remembers whether a backend is reachable before checking again.',
    keywords: ['status', 'ttl', 'available', 'health', 'cache', 'check'],
    tab: 'advanced',
    subTab: 'labs',
    targetSelector: '[data-ega-setting="advanced.backendProbeTtlMs"]',
    type: 'slider',
    defaultValue: `${DEFAULT_SETTINGS.advanced.backendProbeTtlMs}`,
    isModified: { kind: 'eq', path: 'advanced.backendProbeTtlMs' },
  },
  {
    id: 'advanced.cacheSettings',
    label: 'Cache settings',
    description: 'Reuse recent translations within the active browser session.',
    keywords: ['cache', 'reuse', 'enable'],
    tab: 'translate',
    targetSelector: '[data-ega-cache-card]',
    type: 'group',
    isModified: { kind: 'custom', paths: ['cacheEnabled'], fn: (s) => !s.cacheEnabled },
  },
  {
    id: 'advanced.translateTimeoutMs',
    label: 'Text translate timeout',
    description:
      'How long Ega waits for a text reply. 30 s is tight for a reasoning model or a long Summarize or Explain.',
    keywords: ['timeout', 'budget', 'wall-clock', 'text', 'translate'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="advanced.translateTimeoutMs"]',
    type: 'slider',
    isModified: {
      kind: 'fallback',
      path: 'translateTimeoutMs',
      fallback: DEFAULT_TRANSLATE_TIMEOUT_MS,
    },
  },
  {
    id: 'advanced.imageTranslateTimeoutMs',
    label: 'Image translate timeout',
    description: 'How long Ega waits for an image reply.',
    keywords: ['ocr', 'vision', 'image', 'timeout', 'budget'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="advanced.imageTranslateTimeoutMs"]',
    type: 'slider',
    isModified: {
      kind: 'fallback',
      path: 'imageTranslateTimeoutMs',
      fallback: DEFAULT_IMAGE_TRANSLATE_TIMEOUT_MS,
    },
  },
  {
    id: 'advanced.auditLog',
    label: 'Request audit log',
    description: 'The last 50 requests, with the start of each prompt and reply.',
    keywords: ['audit', 'log', 'history', 'request', 'response'],
    tab: 'advanced',
    subTab: 'diagnostics',
    targetSelector: '[data-ega-setting="advanced.auditLog"]',
    type: 'group',
  },
  {
    id: 'advanced.attemptFailures',
    label: 'Attempt failure breakdown',
    description: 'Failed attempts in the last hour, grouped by error.',
    keywords: ['failure', 'attempt', 'retry', 'breakdown', 'error'],
    tab: 'advanced',
    subTab: 'diagnostics',
    targetSelector: '[data-ega-setting="advanced.attemptFailures"]',
    type: 'group',
  },
  {
    id: 'advanced.perBackendStats',
    label: 'Response times',
    description: 'Typical and slowest translate times over recent requests.',
    keywords: ['stats', 'latency', 'histogram', 'p50', 'p95', 'performance'],
    tab: 'advanced',
    subTab: 'diagnostics',
    targetSelector: '[data-ega-setting="advanced.perBackendStats"]',
    type: 'group',
  },
  {
    id: 'advanced.captureResultMeta',
    label: 'Record request details',
    description:
      'Keeps timing, token counts and backend details for the Details drawer and the latency histogram. Turning it off stops the histogram; the request log keeps its last 50 requests.',
    keywords: ['capture', 'meta', 'metadata', 'tokens', 'latency'],
    tab: 'advanced',
    subTab: 'diagnostics',
    targetSelector: '[data-ega-setting="advanced.captureResultMeta"]',
    type: 'toggle',
    // Default is `true`; "modified" means user disabled it.
    isModified: { kind: 'custom', paths: ['captureResultMeta'], fn: (s) => !s.captureResultMeta },
  },
  {
    id: 'advanced.debugLogLevel',
    label: 'Debug log level',
    description:
      'silent, error, warn, info or debug. The debug level logs every streaming chunk to the service worker console and can slow streaming.',
    keywords: ['log', 'debug', 'verbose', 'level'],
    tab: 'advanced',
    subTab: 'diagnostics',
    targetSelector: '[data-ega-setting="advanced.debugLogLevel"]',
    type: 'select',
    defaultValue: DEFAULT_SETTINGS.advanced.debugLogLevel,
    isModified: { kind: 'eq', path: 'advanced.debugLogLevel' },
  },
  {
    id: 'advanced.siteOverrides',
    label: 'Site overrides',
    description: 'Sites where Ega is off or uses its own source language. Review and clear them.',
    keywords: ['site', 'host', 'override', 'per-site', 'domain', 'paused', 'disabled'],
    tab: 'advanced',
    subTab: 'data',
    targetSelector: '[data-ega-per-site-card]',
    type: 'group',
    isModified: { kind: 'nonEmpty', path: 'sitePrefs' },
  },
  {
    id: 'advanced.savedConversations',
    label: 'Saved conversations',
    description: 'Side panel conversations kept on this device, one per site. Delete one or all.',
    keywords: ['conversation', 'chat', 'history', 'thread', 'side panel', 'delete'],
    tab: 'advanced',
    subTab: 'data',
    targetSelector: '[data-ega-setting="advanced.savedConversations"]',
    type: 'group',
  },
  {
    id: 'advanced.dataBackup',
    label: 'Backup & restore',
    description: 'Export or import all settings as a JSON file.',
    keywords: ['backup', 'restore', 'export', 'import', 'json', 'data'],
    tab: 'advanced',
    subTab: 'data',
    targetSelector: '[data-ega-setting="advanced.dataBackup"]',
    type: 'group',
  },
  {
    id: 'advanced.resetEverything',
    label: 'Reset prompt and generation settings',
    description:
      'Resets the Translate prompt (Tasks tab), Effort, temperature and max answer length (Translate tab), and site overrides. Language prompts, API keys and the audit log are kept.',
    keywords: ['reset', 'wipe', 'clear', 'destructive', 'factory'],
    tab: 'advanced',
    subTab: 'data',
    targetSelector: '[data-ega-setting="advanced.resetEverything"]',
    type: 'action',
  },

  // ── About ────────────────────────────────────────────────────────
  {
    id: 'about.clearCache',
    label: 'Clear translation cache',
    description:
      'Delete every cached translation. The next identical request goes to the backend again.',
    keywords: ['cache', 'clear', 'flush', 'translation'],
    tab: 'about',
    type: 'action',
  },
  {
    id: 'about.deleteAllData',
    label: 'Delete all data',
    description: 'Delete everything Ega stores in this browser. This cannot be undone.',
    keywords: ['delete', 'wipe', 'purge', 'data', 'destructive'],
    tab: 'about',
    type: 'action',
  },
  {
    id: 'about.privacy',
    label: 'Privacy',
    description:
      'No telemetry, no analytics, no third-party calls beyond the backend you configure.',
    keywords: ['privacy', 'telemetry', 'analytics', 'tracking'],
    tab: 'about',
    type: 'group',
  },
  {
    id: 'about.licence',
    label: 'License',
    description: 'MIT-licensed open-source project.',
    keywords: ['licence', 'license', 'mit', 'open-source'],
    tab: 'about',
    type: 'group',
  },
  {
    id: 'about.sourceCode',
    label: 'Source code',
    description: 'Link to the project repository.',
    keywords: ['source', 'code', 'repo', 'github'],
    tab: 'about',
    type: 'group',
  },
  {
    id: 'glossary.entries',
    label: 'Glossary entries',
    description:
      'Term → translation pairs Ega adds when the term appears in the text. Use them for brand names, character names and technical terms.',
    keywords: [
      'glossary',
      'term',
      'translation',
      'brand',
      'jargon',
      'consistent',
      'override',
      'name',
    ],
    tab: 'glossary',
    type: 'group',
    isModified: { kind: 'nonEmpty', path: 'glossary' },
  },

  // ── Context menu ─────────────────────────────────────────────────
  {
    id: 'contextMenu.items',
    label: 'Context menu items',
    description: 'Enable, reorder, relabel, and manage right-click menu entries.',
    keywords: ['context', 'menu', 'right-click', 'items', 'reorder', 'enable', 'label'],
    tab: 'translate',
    targetSelector: '[data-ega-cm-layout]',
    type: 'group',
    isModified: { kind: 'jsonStringify', path: 'contextMenuItems' },
  },
  {
    id: 'contextMenu.layout',
    label: 'Context menu layout',
    description:
      'Nested groups items under an Ega ▸ submenu; flat places each item at the top level.',
    keywords: ['context', 'menu', 'layout', 'nested', 'flat', 'submenu', 'right-click'],
    tab: 'translate',
    targetSelector: '[data-ega-cm-layout]',
    type: 'select',
    isModified: {
      kind: 'custom',
      paths: ['contextMenuLayout'],
      fn: (s) => s.contextMenuLayout !== 'nested',
    },
  },
];
