// Source of truth for the settings search/registry; settings-registry.ts interprets it at runtime.

import {
  DEFAULT_BATCH_CONCURRENCY,
  DEFAULT_CONFIDENCE_PILL_THRESHOLD,
  DEFAULT_DESCRIPTION_CONTEXT_CAP,
  DEFAULT_HEADING_TRAIL_DEPTH,
  DEFAULT_HEADING_TRAIL_ENTRY_CAP,
  DEFAULT_IMAGE_TRANSLATE_TIMEOUT_MS,
  DEFAULT_LOCAL_BACKEND_TIMEOUT_MS,
  DEFAULT_SELECTION_CONTEXT_CAP,
  DEFAULT_SMART_BUBBLE_MIN_LENGTH,
  DEFAULT_STREAMING_FLUSH_MS,
  DEFAULT_TRANSLATE_TIMEOUT_MS,
} from './constants';
import { DEFAULT_SETTINGS } from './settings-defaults';
import { isMenuModified, withShippedIds } from './context-menu-names';
import { DEFAULT_TEMPLATE } from './prompts';
import type { SettingsTab } from './settings-tabs';
import type { Settings } from './types';

export type { SettingsTab };

/** `action` is a button that does something once (reset, clear, delete), not a value. */
export type SettingType = 'toggle' | 'slider' | 'select' | 'text' | 'template' | 'group' | 'action';

export type AdvancedSubTab = 'diagnostics' | 'data';

/** `fallback` is the shipped default the stored value is compared against by value.
 *  `custom.paths` lists what `fn` reads — the coverage gate cannot see inside it. */
export type IsModifiedSpec =
  | { kind: 'eq'; path: string }
  | { kind: 'fallback'; path: string; fallback: number }
  | { kind: 'nonEmpty'; path: string }
  | { kind: 'jsonStringify'; path: string }
  | { kind: 'custom'; paths: readonly string[]; fn: (s: Settings) => boolean };

export interface SettingEntrySpec {
  readonly id: string;
  readonly label: string;
  readonly description: string;
  readonly keywords: readonly string[];
  readonly tab: SettingsTab;
  readonly subTab?: AdvancedSubTab;
  /** Lives outside every tab: Enter in search focuses it there. */
  readonly location?: 'header';
  readonly targetSelector?: string;
  readonly type: SettingType;
  readonly defaultValue?: string;
  readonly isModified?: IsModifiedSpec;
}

export const SETTINGS_SPEC: readonly SettingEntrySpec[] = [
  // ── Display ──────────────────────────────────────────────────────
  {
    id: 'display.bubbleMode',
    label: 'Selection bubble',
    description: 'When the floating bubble appears after you select text',
    keywords: ['bubble', 'selection', 'smart', 'always', 'never', 'popup', 'show'],
    tab: 'selection-bubble',
    type: 'select',
    isModified: { kind: 'eq', path: 'bubbleMode' },
  },
  {
    id: 'display.pickerEnabled',
    label: 'Turn on the element picker',
    description: 'Hover an element to outline it, click to translate, Esc cancels',
    keywords: ['picker', 'element', 'click', 'pick', 'hover'],
    tab: 'selection-bubble',
    targetSelector: '[data-ega-setting="display.pickerEnabled"]',
    type: 'toggle',
    isModified: { kind: 'eq', path: 'pickerEnabled' },
  },
  {
    id: 'display.pickerShortcut',
    label: 'Element picker shortcut',
    description: 'Starts the element picker on a web page',
    keywords: ['picker', 'shortcut', 'keybinding', 'hotkey'],
    tab: 'selection-bubble',
    targetSelector: '[data-ega-setting="display.pickerShortcut"]',
    type: 'text',
    isModified: { kind: 'eq', path: 'pickerShortcut' },
  },
  {
    id: 'display.shortcut',
    label: 'Translate selection',
    description: 'Translates the selected text on a web page',
    keywords: ['shortcut', 'keybinding', 'hotkey', 'translate', 'key'],
    tab: 'selection-bubble',
    targetSelector: '[data-ega-setting="display.shortcut"]',
    type: 'text',
    isModified: { kind: 'eq', path: 'shortcut' },
  },
  {
    id: 'display.theme',
    label: 'Theme',
    description: 'Light, dark, or the same as your system',
    keywords: ['dark', 'light', 'colour', 'color', 'mode', 'theme'],
    tab: 'about',
    location: 'header',
    type: 'select',
    isModified: { kind: 'eq', path: 'theme' },
  },
  {
    id: 'display.defaultDisplayMode',
    label: 'Where answers show',
    description: 'A tooltip over the selection, or the answer in place of the text',
    keywords: ['tooltip', 'inline', 'surface', 'display', 'mode'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="display.defaultDisplayMode"]',
    type: 'select',
    isModified: { kind: 'eq', path: 'defaultDisplayMode' },
  },
  {
    id: 'display.streaming',
    label: 'Stream the answer live',
    description: 'Show the answer while the model writes it',
    keywords: ['streaming', 'stream', 'token', 'live'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="display.streaming"]',
    type: 'toggle',
    isModified: { kind: 'eq', path: 'streaming' },
  },
  {
    id: 'display.streamingFlushMs',
    label: 'Show new text every',
    description: '0 is instant; above 100 ms streaming looks stuck',
    keywords: ['streaming', 'flush', 'paint', 'render', 'speed'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="display.streamingFlushMs"]',
    type: 'slider',
    isModified: {
      kind: 'fallback',
      path: 'streamingFlushMs',
      fallback: DEFAULT_STREAMING_FLUSH_MS,
    },
  },
  {
    id: 'display.confidencePill',
    label: 'Show confidence pill',
    description: 'How sure the model is, shown next to each answer',
    keywords: ['confidence', 'pill', 'badge', 'score'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="display.confidencePill"]',
    type: 'toggle',
    isModified: { kind: 'eq', path: 'confidencePill' },
  },
  {
    id: 'display.confidencePillThreshold',
    label: 'Hide the pill below',
    description: '0 shows the pill on every answer',
    keywords: ['confidence', 'threshold', 'score'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="display.confidencePillThreshold"]',
    type: 'slider',
    // (s.confidencePillThreshold ?? DEFAULT) !== DEFAULT collapses to "value set and not the default"
    isModified: {
      kind: 'fallback',
      path: 'confidencePillThreshold',
      fallback: DEFAULT_CONFIDENCE_PILL_THRESHOLD,
    },
  },
  {
    id: 'display.tooltipShowSource',
    label: 'Show the original text at the top',
    description: 'The tooltip repeats the text you selected above the answer',
    keywords: ['source', 'original', 'tooltip', 'echo'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="display.tooltipShowSource"]',
    type: 'toggle',
    isModified: { kind: 'eq', path: 'tooltipShowSource' },
  },
  {
    id: 'display.tooltipClickOutside',
    label: 'Close when I click outside',
    description: 'Hides the close button',
    keywords: ['click', 'outside', 'dismiss', 'tooltip', 'close'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="display.tooltipClickOutside"]',
    type: 'toggle',
    isModified: { kind: 'eq', path: 'tooltipClickOutside' },
  },
  {
    id: 'display.tooltipDraggable',
    label: 'Let me drag the tooltip',
    description: 'Move the tooltip by its handle on the left edge',
    keywords: ['drag', 'tooltip', 'move', 'reposition'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="display.tooltipDraggable"]',
    type: 'toggle',
    isModified: { kind: 'eq', path: 'tooltipDraggable' },
  },
  {
    id: 'display.contextEnabled',
    label: 'Send page context',
    description: 'Sends the page title, address and nearby text with your request',
    keywords: ['context', 'page', 'metadata', 'surrounding'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="display.contextEnabled"]',
    type: 'toggle',
    isModified: { kind: 'eq', path: 'contextEnabled' },
  },
  {
    id: 'display.explainUsesPageImage',
    label: 'Send the page image with Explain',
    description: 'Explain on selected text also sends the main image of the page',
    keywords: ['explain', 'image', 'picture', 'vision', 'post', 'meme'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="display.explainUsesPageImage"]',
    type: 'toggle',
    isModified: { kind: 'eq', path: 'explainUsesPageImage' },
  },
  {
    id: 'display.pageContextLevel',
    label: 'How much page context',
    description:
      'Minimal sends the title, address and nearby text; Rich adds headings and the post',
    keywords: ['context', 'depth', 'level', 'minimal', 'rich', 'page'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="display.pageContextLevel"]',
    type: 'select',
    defaultValue: DEFAULT_SETTINGS.pageContextLevel,
    isModified: { kind: 'eq', path: 'pageContextLevel' },
  },
  {
    id: 'display.pageTranslateMode',
    label: 'Show the translation',
    description: 'In place replaces each block; Under the original adds the translation below it',
    keywords: ['page', 'translate', 'inplace', 'bilingual', 'render', 'mode', 'side by side'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="display.pageTranslateMode"]',
    type: 'select',
    defaultValue: DEFAULT_SETTINGS.pageTranslateMode,
    isModified: { kind: 'eq', path: 'pageTranslateMode' },
  },
  // ── Defaults ─────────────────────────────────────────────────────
  {
    id: 'defaults.defaultLang',
    label: 'Default source language',
    description: 'The language of the text when you do not pick one; Auto-detect guesses it',
    keywords: ['source', 'language', 'auto', 'detect', 'default'],
    tab: 'languages',
    targetSelector: '[data-ega-setting="defaults.defaultLang"]',
    type: 'select',
    isModified: { kind: 'eq', path: 'defaultLang' },
  },
  {
    id: 'defaults.defaultTargetLang',
    label: 'Default target language',
    description: 'The language Ega answers in when you do not pick one',
    keywords: ['target', 'language', 'destination', 'default'],
    tab: 'languages',
    targetSelector: '[data-ega-setting="defaults.defaultTargetLang"]',
    type: 'select',
    isModified: { kind: 'eq', path: 'defaultTargetLang' },
  },
  {
    id: 'defaults.defaultTask',
    label: 'Default task',
    description: 'What runs when you do not pick a task',
    keywords: ['task', 'translate', 'explain', 'summarize', 'reword', 'grammar', 'default'],
    tab: 'tasks',
    targetSelector: '[data-ega-setting="defaults.defaultTask"]',
    type: 'select',
    isModified: { kind: 'eq', path: 'defaultTask' },
  },
  {
    id: 'defaults.defaultTone',
    label: 'Default tone',
    description: 'The tone a task uses unless you pick another, like formal or casual',
    keywords: ['tone', 'reword', 'formal', 'casual', 'voice'],
    tab: 'tasks',
    targetSelector: '[data-ega-setting="defaults.defaultTone"]',
    type: 'select',
    isModified: { kind: 'eq', path: 'defaultTone' },
  },
  {
    id: 'tasks.enabled',
    label: 'Tasks on and off',
    description: 'An off task is hidden in every picker and menu',
    keywords: ['task', 'off', 'hide', 'disable', 'picker'],
    tab: 'tasks',
    targetSelector: '[data-ega-setting="tasks.enabled"]',
    type: 'group',
    isModified: { kind: 'nonEmpty', path: 'disabledTasks' },
  },
  {
    id: 'tasks.overrides',
    label: 'Task settings',
    description: 'Per task: effort, page context and glossary',
    keywords: ['task', 'effort', 'page context', 'glossary', 'reset'],
    tab: 'tasks',
    targetSelector: '[data-ega-setting="tasks.overrides"]',
    type: 'group',
    isModified: { kind: 'nonEmpty', path: 'taskOverrides' },
  },
  {
    id: 'tasks.backupRestore',
    label: 'Backup and restore tasks',
    description: 'Your tasks, their edits and on/off state',
    keywords: ['backup', 'restore', 'export', 'import', 'json', 'task'],
    tab: 'tasks',
    type: 'group',
  },

  // ── Backends ─────────────────────────────────────────────────────
  {
    id: 'backends.backendOrder',
    label: 'Backends in use',
    description:
      'The backends Ega tries, from the top of the list; drag or use the arrows to reorder',
    keywords: ['backend', 'order', 'priority', 'fallback', 'chain', 'drag'],
    tab: 'backends',
    targetSelector: '[data-ega-setting="backends.backendOrder"]',
    type: 'group',
    isModified: { kind: 'jsonStringify', path: 'backendOrder' },
  },
  {
    id: 'backends.disabledBackends',
    label: 'Backends not in use',
    description: 'Ega never sends text to these',
    keywords: ['disabled', 'backend', 'exclude', 'off'],
    tab: 'backends',
    targetSelector: '[data-ega-setting="backends.disabledBackends"]',
    type: 'group',
    // The default list is non-empty, so compare contents, not emptiness.
    isModified: { kind: 'jsonStringify', path: 'disabledBackends' },
  },
  {
    id: 'backends.model',
    label: 'Model per backend',
    description: 'Which model each backend calls, set on its row',
    keywords: ['model', 'id', 'gpt', 'claude', 'gemini', 'llama', 'pick', 'choose'],
    tab: 'backends',
    targetSelector: '[data-ega-model-combobox]',
    type: 'select',
    isModified: { kind: 'jsonStringify', path: 'model' },
  },
  {
    id: 'backends.anthropicApiKey',
    label: 'Anthropic API key',
    description: 'Your Anthropic API key, kept in this browser',
    keywords: ['anthropic', 'claude', 'api', 'key', 'auth', 'cloud'],
    tab: 'backends',
    targetSelector: '[data-ega-api-key="anthropic"]',
    type: 'text',
    isModified: { kind: 'nonEmpty', path: 'anthropicApiKey' },
  },
  {
    id: 'backends.openaiApiKey',
    label: 'OpenAI API key',
    description: 'Your OpenAI API key, kept in this browser',
    keywords: ['openai', 'gpt', 'api', 'key', 'auth', 'cloud'],
    tab: 'backends',
    targetSelector: '[data-ega-api-key="openai"]',
    type: 'text',
    isModified: { kind: 'nonEmpty', path: 'openaiApiKey' },
  },
  {
    id: 'backends.geminiApiKey',
    label: 'Gemini API key',
    description: 'Your Gemini API key, kept in this browser',
    keywords: ['gemini', 'google', 'api', 'key', 'auth', 'cloud'],
    tab: 'backends',
    targetSelector: '[data-ega-api-key="gemini"]',
    type: 'text',
    isModified: { kind: 'nonEmpty', path: 'geminiApiKey' },
  },
  {
    id: 'backends.groqApiKey',
    label: 'Groq API key',
    description: 'Your Groq API key, kept in this browser',
    keywords: ['groq', 'api', 'key', 'auth', 'cloud'],
    tab: 'backends',
    targetSelector: '[data-ega-api-key="groq"]',
    type: 'text',
    isModified: { kind: 'nonEmpty', path: 'groqApiKey' },
  },
  {
    id: 'backends.deepseekApiKey',
    label: 'DeepSeek API key',
    description: 'Your DeepSeek API key, kept in this browser',
    keywords: ['deepseek', 'api', 'key', 'auth', 'cloud'],
    tab: 'backends',
    targetSelector: '[data-ega-api-key="deepseek"]',
    type: 'text',
    isModified: { kind: 'nonEmpty', path: 'deepseekApiKey' },
  },
  {
    id: 'backends.togetherApiKey',
    label: 'Together API key',
    description: 'Your Together API key, kept in this browser',
    keywords: ['together', 'api', 'key', 'auth', 'cloud'],
    tab: 'backends',
    targetSelector: '[data-ega-api-key="together"]',
    type: 'text',
    isModified: { kind: 'nonEmpty', path: 'togetherApiKey' },
  },
  {
    id: 'backends.mistralApiKey',
    label: 'Mistral API key',
    description: 'Your Mistral API key, kept in this browser',
    keywords: ['mistral', 'api', 'key', 'auth', 'cloud'],
    tab: 'backends',
    targetSelector: '[data-ega-api-key="mistral"]',
    type: 'text',
    isModified: { kind: 'nonEmpty', path: 'mistralApiKey' },
  },
  {
    id: 'backends.xaiApiKey',
    label: 'xAI API key',
    description: 'Your xAI API key, kept in this browser',
    keywords: ['xai', 'grok', 'api', 'key', 'auth', 'cloud'],
    tab: 'backends',
    targetSelector: '[data-ega-api-key="xai"]',
    type: 'text',
    isModified: { kind: 'nonEmpty', path: 'xaiApiKey' },
  },
  {
    id: 'backends.fireworksApiKey',
    label: 'Fireworks API key',
    description: 'Your Fireworks API key, kept in this browser',
    keywords: ['fireworks', 'api', 'key', 'auth', 'cloud'],
    tab: 'backends',
    targetSelector: '[data-ega-api-key="fireworks"]',
    type: 'text',
    isModified: { kind: 'nonEmpty', path: 'fireworksApiKey' },
  },
  {
    id: 'backends.openrouterApiKey',
    label: 'OpenRouter API key',
    description: 'Your OpenRouter API key, kept in this browser',
    keywords: ['openrouter', 'api', 'key', 'auth', 'cloud'],
    tab: 'backends',
    targetSelector: '[data-ega-api-key="openrouter"]',
    type: 'text',
    isModified: { kind: 'nonEmpty', path: 'openrouterApiKey' },
  },
  {
    id: 'backends.ollamaUrl',
    label: 'Ollama URL',
    description: 'Where your Ollama server listens; the default is http://localhost:11434',
    keywords: ['ollama', 'local', 'url', 'endpoint', 'daemon'],
    tab: 'backends',
    targetSelector: '[data-ega-setting="backends.ollamaUrl"]',
    type: 'text',
    // Nullable string compared with nullable default — collapse both sides via ?? ''.
    isModified: {
      kind: 'custom',
      paths: ['ollamaUrl'],
      fn: (s) => (s.ollamaUrl ?? '') !== (DEFAULT_SETTINGS.ollamaUrl ?? ''),
    },
  },
  {
    id: 'backends.localServerUrl',
    label: 'Local server URL',
    description: 'Where your OpenAI-compatible server listens, such as LM Studio or llama-server',
    keywords: [
      'local',
      'server',
      'url',
      'lm studio',
      'lmstudio',
      'llama.cpp',
      'llama-server',
      'openai',
    ],
    tab: 'backends',
    targetSelector: '[data-ega-setting="backends.localServerUrl"]',
    type: 'text',
    isModified: {
      kind: 'custom',
      paths: ['localServerUrl'],
      fn: (s) => (s.localServerUrl ?? '') !== (DEFAULT_SETTINGS.localServerUrl ?? ''),
    },
  },
  {
    id: 'backends.nativeCli',
    label: 'Native host CLI',
    description: 'Which CLI the native host runs: Claude Code or Codex',
    keywords: ['native', 'host', 'claude', 'codex', 'cli'],
    tab: 'backends',
    targetSelector: '[data-ega-setting="backends.nativeCli"]',
    type: 'select',
    isModified: { kind: 'eq', path: 'nativeCli' },
  },
  {
    id: 'backends.localBackendTimeoutMs',
    label: 'Local check timeout',
    description: 'Raise it if local backends time out after the computer wakes',
    keywords: ['local', 'native', 'ollama', 'server', 'timeout', 'check', 'reachable'],
    tab: 'backends',
    targetSelector: '[data-ega-setting="backends.localBackendTimeoutMs"]',
    type: 'slider',
    isModified: {
      kind: 'fallback',
      path: 'localBackendTimeoutMs',
      fallback: DEFAULT_LOCAL_BACKEND_TIMEOUT_MS,
    },
  },
  {
    id: 'backends.preWarmNative',
    label: 'Start the native host with Chrome',
    description: 'Faster first answer, uses some battery',
    keywords: ['pre-warm', 'prewarm', 'warm', 'native', 'cold', 'start', 'boot', 'spawn'],
    tab: 'backends',
    targetSelector: '[data-ega-setting="backends.preWarmNative"]',
    type: 'toggle',
    // Default is `true` → "modified" means user disabled it.
    isModified: { kind: 'custom', paths: ['preWarmNative'], fn: (s) => s.preWarmNative === false },
  },
  // ── Languages ────────────────────────────────────────────────────
  {
    id: 'languages.varieties',
    label: 'Slang and special languages',
    description: 'Shown in the language pickers next to the standard languages',
    keywords: ['variety', 'dialect', 'language', 'custom'],
    tab: 'languages',
    type: 'group',
  },
  {
    id: 'languages.disabledVarieties',
    label: 'Languages hidden from pickers',
    description: 'Hidden languages are left out of the language pickers and auto-detect',
    keywords: ['disabled', 'variety', 'off', 'skip'],
    tab: 'languages',
    type: 'group',
    isModified: { kind: 'nonEmpty', path: 'disabledVarieties' },
  },
  {
    id: 'languages.customLanguages',
    label: 'Custom languages',
    description: 'Languages you added yourself',
    keywords: ['custom', 'variety', 'add', 'user'],
    tab: 'languages',
    type: 'group',
  },
  {
    id: 'languages.varietyOverrides',
    label: 'Edits to built-in languages',
    description: 'Your notes, examples and detection patterns for a built-in language',
    keywords: ['override', 'variety', 'edit', 'hint', 'example'],
    tab: 'languages',
    type: 'group',
    isModified: { kind: 'nonEmpty', path: 'varietyOverrides' },
  },
  {
    id: 'languages.backupRestore',
    label: 'Backup and restore languages',
    description: 'Your custom languages, edits and language prompts',
    keywords: ['backup', 'restore', 'export', 'import', 'json'],
    tab: 'languages',
    type: 'group',
  },

  // ── Advanced ─────────────────────────────────────────────────────
  {
    id: 'advanced.promptTemplate',
    label: 'Translate prompt',
    description: 'The prompt Translate, Explain and every language without its own prompt use',
    keywords: ['template', 'prompt', 'system', 'user', 'slot', 'global'],
    tab: 'tasks',
    targetSelector: '[data-ega-task-item="translate"]',
    type: 'template',
    isModified: {
      kind: 'custom',
      paths: ['advanced.promptTemplate'],
      fn: (s) =>
        s.advanced.promptTemplate.system !== DEFAULT_TEMPLATE.system ||
        s.advanced.promptTemplate.user !== DEFAULT_TEMPLATE.user,
    },
  },
  {
    id: 'advanced.perPresetTemplates',
    label: 'Prompt for one language',
    description: 'Edit a language and pick "Use its own prompt" to change only what it sends',
    keywords: ['preset', 'template', 'override', 'per-preset', 'language', 'prompt'],
    tab: 'languages',
    type: 'template',
    isModified: { kind: 'nonEmpty', path: 'advanced.perPresetTemplates' },
  },
  {
    id: 'advanced.rules',
    label: 'Rules',
    description: 'Extra instructions for every task or only some; each can be limited to sites',
    keywords: ['rule', 'rules', 'always', 'never', 'prefer', 'format', 'declarative'],
    tab: 'glossary',
    targetSelector: '[data-ega-setting="tasks.rules"]',
    type: 'group',
    isModified: { kind: 'nonEmpty', path: 'advanced.rules' },
  },
  {
    id: 'advanced.temperature',
    label: 'Creativity (temperature)',
    description: 'Lower is more predictable; above 1.2 answers can break',
    keywords: ['creativity', 'random', 'heat', 'sampling', 'temperature'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="advanced.temperature"]',
    type: 'slider',
    defaultValue: String(DEFAULT_SETTINGS.advanced.temperature),
    // The 0.05 slider step lands on 0.30000000000000004, so a strict !== would flag the visible default.
    isModified: {
      kind: 'custom',
      paths: ['advanced.temperature'],
      fn: (s) => Math.abs(s.advanced.temperature - DEFAULT_SETTINGS.advanced.temperature) >= 1e-9,
    },
  },
  {
    id: 'advanced.maxTokens',
    label: 'Longest answer',
    description: 'Answers longer than this are cut short',
    keywords: ['length', 'output', 'tokens', 'max tokens', 'cap', 'max'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="advanced.maxTokens"]',
    type: 'slider',
    defaultValue: String(DEFAULT_SETTINGS.advanced.maxTokens),
    isModified: { kind: 'eq', path: 'advanced.maxTokens' },
  },
  {
    id: 'advanced.effort',
    label: 'Effort',
    description: 'More effort is slower and costs more',
    keywords: [
      'reasoning',
      'thinking level',
      'gemini',
      'effort',
      'thinking',
      'openai',
      'o-series',
      'gpt-5',
      'gpt-6',
      'gpt-oss',
      'anthropic',
      'claude',
    ],
    tab: 'translate',
    targetSelector: '[data-ega-setting="advanced.effort"]',
    type: 'select',
    defaultValue: String(DEFAULT_SETTINGS.advanced.effort),
    isModified: { kind: 'eq', path: 'advanced.effort' },
  },
  {
    id: 'advanced.batchConcurrency',
    label: 'Areas sent at once',
    description: 'More is faster and uses more of your quota',
    keywords: ['concurrency', 'parallel', 'workers', 'batch', 'page-translate'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="advanced.batchConcurrency"]',
    type: 'slider',
    isModified: {
      kind: 'fallback',
      path: 'batchConcurrency',
      fallback: DEFAULT_BATCH_CONCURRENCY,
    },
  },
  {
    id: 'advanced.smartBubbleMinLength',
    label: 'Shortest selection',
    description: 'Smart hides the bubble on shorter selections in Latin letters',
    keywords: ['smart', 'bubble', 'length', 'short', 'min', 'characters'],
    tab: 'selection-bubble',
    targetSelector: '[data-ega-setting="advanced.smartBubbleMinLength"]',
    type: 'slider',
    isModified: {
      kind: 'fallback',
      path: 'smartBubbleMinLength',
      fallback: DEFAULT_SMART_BUBBLE_MIN_LENGTH,
    },
  },
  {
    id: 'advanced.pageContextPayload',
    label: 'Fine-tune what is sent',
    description: 'Limits for nearby text, the page description and headings',
    keywords: ['context', 'payload', 'cap', 'page', 'heading', 'description'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="advanced.pageContextPayload"]',
    type: 'group',
    isModified: {
      kind: 'custom',
      paths: [
        'selectionContextCap',
        'descriptionContextCap',
        'headingTrailDepth',
        'headingTrailEntryCap',
      ],
      fn: (s) =>
        (s.selectionContextCap !== undefined &&
          s.selectionContextCap !== DEFAULT_SELECTION_CONTEXT_CAP) ||
        (s.descriptionContextCap !== undefined &&
          s.descriptionContextCap !== DEFAULT_DESCRIPTION_CONTEXT_CAP) ||
        (s.headingTrailDepth !== undefined &&
          s.headingTrailDepth !== DEFAULT_HEADING_TRAIL_DEPTH) ||
        (s.headingTrailEntryCap !== undefined &&
          s.headingTrailEntryCap !== DEFAULT_HEADING_TRAIL_ENTRY_CAP),
    },
  },
  {
    id: 'advanced.selectionContextCap',
    label: 'Selection window',
    description: 'Text sent from before and after the selection',
    keywords: ['selection', 'window', 'neighbourhood', 'cap', 'context', 'chars'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="advanced.selectionContextCap"]',
    type: 'slider',
    isModified: {
      kind: 'fallback',
      path: 'selectionContextCap',
      fallback: DEFAULT_SELECTION_CONTEXT_CAP,
    },
  },
  {
    id: 'advanced.descriptionContextCap',
    label: 'Page description length',
    description: 'Longest page description sent; used only with Rich',
    keywords: ['description', 'meta', 'cap', 'context', 'chars', 'rich'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="advanced.descriptionContextCap"]',
    type: 'slider',
    isModified: {
      kind: 'fallback',
      path: 'descriptionContextCap',
      fallback: DEFAULT_DESCRIPTION_CONTEXT_CAP,
    },
  },
  {
    id: 'advanced.headingTrailDepth',
    label: 'Headings sent',
    description: 'How many of the nearest headings are sent; used only with Rich',
    keywords: ['heading', 'trail', 'depth', 'context', 'rich', 'h1'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="advanced.headingTrailDepth"]',
    type: 'slider',
    isModified: {
      kind: 'fallback',
      path: 'headingTrailDepth',
      fallback: DEFAULT_HEADING_TRAIL_DEPTH,
    },
  },
  {
    id: 'advanced.headingTrailEntryCap',
    label: 'Longest heading',
    description: 'Longer headings are cut to this length; used only with Rich',
    keywords: ['heading', 'trail', 'cap', 'chars', 'context'],
    tab: 'translate',
    targetSelector: '[data-ega-setting="advanced.headingTrailEntryCap"]',
    type: 'slider',
    isModified: {
      kind: 'fallback',
      path: 'headingTrailEntryCap',
      fallback: DEFAULT_HEADING_TRAIL_ENTRY_CAP,
    },
  },
  {
    id: 'advanced.retryCount',
    label: 'Try up to N backends',
    description: 'How many backends one request may try, from the top of the list',
    keywords: ['retry', 'fallback', 'chain', 'rate-limit', 'network', 'attempts'],
    tab: 'backends',
    targetSelector: '[data-ega-setting="advanced.retryCount"]',
    type: 'slider',
    defaultValue: String(DEFAULT_SETTINGS.advanced.retryCount),
    isModified: { kind: 'eq', path: 'advanced.retryCount' },
  },
  {
    id: 'advanced.backendProbeTtlMs',
    label: 'Remember backend status for',
    description: 'Lower checks more often; higher notices a backend coming back later',
    keywords: ['status', 'ttl', 'available', 'health', 'cache', 'check'],
    tab: 'backends',
    targetSelector: '[data-ega-setting="advanced.backendProbeTtlMs"]',
    type: 'slider',
    defaultValue: `${DEFAULT_SETTINGS.advanced.backendProbeTtlMs}`,
    isModified: { kind: 'eq', path: 'advanced.backendProbeTtlMs' },
  },
  {
    id: 'advanced.cacheSettings',
    label: 'Reuse recent answers',
    description: 'The same text gets the same answer for 5 minutes',
    keywords: ['cache', 'reuse', 'enable'],
    tab: 'translate',
    targetSelector: '[data-ega-cache-card]',
    type: 'group',
    isModified: { kind: 'custom', paths: ['cacheEnabled'], fn: (s) => !s.cacheEnabled },
  },
  {
    id: 'advanced.translateTimeoutMs',
    label: 'Text answer timeout',
    description: 'Raise it for reasoning models and long summaries',
    keywords: ['timeout', 'budget', 'wall-clock', 'text', 'translate'],
    tab: 'backends',
    targetSelector: '[data-ega-setting="advanced.translateTimeoutMs"]',
    type: 'slider',
    isModified: {
      kind: 'fallback',
      path: 'translateTimeoutMs',
      fallback: DEFAULT_TRANSLATE_TIMEOUT_MS,
    },
  },
  {
    id: 'advanced.imageTranslateTimeoutMs',
    label: 'Image answer timeout',
    description: 'Images take longer than text',
    keywords: ['ocr', 'vision', 'image', 'timeout', 'budget'],
    tab: 'backends',
    targetSelector: '[data-ega-setting="advanced.imageTranslateTimeoutMs"]',
    type: 'slider',
    isModified: {
      kind: 'fallback',
      path: 'imageTranslateTimeoutMs',
      fallback: DEFAULT_IMAGE_TRANSLATE_TIMEOUT_MS,
    },
  },
  {
    id: 'advanced.auditLog',
    label: 'Recent requests',
    description: 'The last 50 requests, kept on this computer',
    keywords: ['audit', 'log', 'history', 'request', 'response'],
    tab: 'advanced',
    subTab: 'diagnostics',
    targetSelector: '[data-ega-setting="advanced.auditLog"]',
    type: 'group',
  },
  {
    id: 'advanced.attemptFailures',
    label: 'Recent errors',
    description: 'Errors in the last hour',
    keywords: ['failure', 'attempt', 'retry', 'breakdown', 'error'],
    tab: 'advanced',
    subTab: 'diagnostics',
    targetSelector: '[data-ega-setting="advanced.attemptFailures"]',
    type: 'group',
  },
  {
    id: 'advanced.perBackendStats',
    label: 'Response times',
    description: 'Typical and slowest times since Ega last started',
    keywords: ['stats', 'latency', 'histogram', 'p50', 'p95', 'performance'],
    tab: 'advanced',
    subTab: 'diagnostics',
    targetSelector: '[data-ega-setting="advanced.perBackendStats"]',
    type: 'group',
  },
  {
    id: 'advanced.captureResultMeta',
    label: 'Record request details',
    description: 'Keeps timing and token counts for each request',
    keywords: ['capture', 'meta', 'metadata', 'tokens', 'latency'],
    tab: 'advanced',
    subTab: 'diagnostics',
    targetSelector: '[data-ega-setting="advanced.captureResultMeta"]',
    type: 'toggle',
    // Default is `true`; "modified" means user disabled it.
    isModified: { kind: 'custom', paths: ['captureResultMeta'], fn: (s) => !s.captureResultMeta },
  },
  {
    id: 'advanced.debugLogLevel',
    label: 'Log detail',
    description:
      'How much Ega logs to the service worker console; Everything logs every streaming chunk and can slow answers',
    keywords: ['log', 'debug', 'verbose', 'level'],
    tab: 'advanced',
    subTab: 'diagnostics',
    targetSelector: '[data-ega-setting="advanced.debugLogLevel"]',
    type: 'select',
    defaultValue: DEFAULT_SETTINGS.advanced.debugLogLevel,
    isModified: { kind: 'eq', path: 'advanced.debugLogLevel' },
  },
  {
    id: 'advanced.siteOverrides',
    label: 'Site overrides',
    description: 'Sites where Ega is off or uses its own source language',
    keywords: ['site', 'host', 'override', 'per-site', 'domain', 'paused', 'disabled'],
    tab: 'advanced',
    subTab: 'data',
    targetSelector: '[data-ega-per-site-card]',
    type: 'group',
    isModified: { kind: 'nonEmpty', path: 'sitePrefs' },
  },
  {
    id: 'advanced.savedConversations',
    label: 'Saved conversations',
    description: 'Side panel conversations kept on this computer',
    keywords: ['conversation', 'chat', 'history', 'thread', 'side panel', 'delete'],
    tab: 'advanced',
    subTab: 'data',
    targetSelector: '[data-ega-setting="advanced.savedConversations"]',
    type: 'group',
  },
  {
    id: 'advanced.dataBackup',
    label: 'Backup and restore',
    description: 'Every setting in one file',
    keywords: ['backup', 'restore', 'export', 'import', 'json', 'data'],
    tab: 'advanced',
    subTab: 'data',
    targetSelector: '[data-ega-setting="advanced.dataBackup"]',
    type: 'group',
  },
  {
    id: 'advanced.resetEverything',
    label: 'Reset prompt and model settings',
    description: 'Puts back the Translate prompt, Effort, creativity and answer length',
    keywords: ['reset', 'wipe', 'clear', 'destructive', 'factory'],
    tab: 'advanced',
    subTab: 'data',
    targetSelector: '[data-ega-setting="advanced.resetEverything"]',
    type: 'action',
  },

  // ── About ────────────────────────────────────────────────────────
  {
    id: 'about.clearCache',
    label: 'Clear saved answers',
    description: 'Translations run again next time',
    keywords: ['cache', 'clear', 'flush', 'translation'],
    tab: 'advanced',
    targetSelector: '[data-ega-setting="about.clearCache"]',
    subTab: 'data',
    type: 'action',
  },
  {
    id: 'about.deleteAllData',
    label: 'Delete all data',
    description: 'Removes every setting, key and saved conversation',
    keywords: ['delete', 'wipe', 'purge', 'data', 'destructive'],
    tab: 'advanced',
    targetSelector: '[data-ega-setting="about.deleteAllData"]',
    subTab: 'data',
    type: 'action',
  },
  {
    id: 'about.privacy',
    label: 'Privacy',
    description: 'No telemetry, no cloud sync, no analytics',
    keywords: ['privacy', 'telemetry', 'analytics', 'tracking'],
    tab: 'about',
    targetSelector: '[data-ega-setting="about.privacy"]',
    type: 'group',
  },
  {
    id: 'about.licence',
    label: 'License',
    description: 'Open source under the MIT license',
    keywords: ['licence', 'license', 'mit', 'open-source'],
    tab: 'about',
    targetSelector: '[data-ega-license-link]',
    type: 'group',
  },
  {
    id: 'about.sourceCode',
    label: 'Source code',
    description: 'The project repository on GitHub',
    keywords: ['source', 'code', 'repo', 'github'],
    tab: 'about',
    targetSelector: '[data-ega-source-link]',
    type: 'group',
  },
  {
    id: 'glossary.entries',
    label: 'Glossary entries',
    description: 'Terms Ega always translates the same way',
    keywords: [
      'glossary',
      'term',
      'translation',
      'brand',
      'jargon',
      'consistent',
      'override',
      'name',
    ],
    tab: 'glossary',
    type: 'group',
    isModified: { kind: 'nonEmpty', path: 'glossary' },
  },

  // ── Right-click menu ─────────────────────────────────────────────
  {
    id: 'contextMenu.items',
    label: 'Right-click menu',
    description: "Show, hide, order and add the items Ega puts in Chrome's right-click menu",
    keywords: [
      'context',
      'context menu',
      'menu',
      'right-click',
      'items',
      'reorder',
      'enable',
      'label',
      'image',
      'side panel',
      'tooltip',
      'opens in',
      'explain',
    ],
    tab: 'selection-bubble',
    targetSelector: '[data-ega-setting="contextMenu.items"]',
    type: 'group',
    isModified: {
      kind: 'custom',
      paths: ['contextMenuItems'],
      // The card reads the same view: a shipped row an older version re-minted is not a change.
      fn: (s) => isMenuModified(withShippedIds(s.contextMenuItems)),
    },
  },
  {
    id: 'contextMenu.images',
    label: 'Where image actions open',
    description: 'Side panel or a tooltip on the image, per right-click image action',
    keywords: ['image', 'ocr', 'sidepanel', 'tooltip', 'surface', 'opens in'],
    tab: 'selection-bubble',
    targetSelector: '[data-ega-cm-group="image"]',
    type: 'group',
  },
];
