/** Rebuilds src/content/english-lexicon.txt from SCOWL; run with `pnpm gen:english-lexicon` (downloads once, then reads the cache). */

import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { gunzipSync } from 'node:zlib';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'src/content/english-lexicon.txt');
const NOTICE_OUT = path.join(ROOT, 'scripts/english-lexicon/SCOWL-Copyright.txt');

const VERSION = '2020.12.07';
const URL = `https://downloads.sourceforge.net/project/wordlist/SCOWL/${VERSION}/scowl-${VERSION}.tar.gz`;
const SHA256 = '5587667caa20c4891390c2d42dbb4d5c4c3f41bee77af1457ece3ba23fb859cc';
const CACHE = path.join(os.tmpdir(), `scowl-${VERSION}.tar.gz`);

// Size 10 is most common, 95 rarest; upper-case and abbreviation lists past 35 are mostly names, many Arabic.
const LISTS: Record<string, number> = {
  'english-words': 50,
  'american-words': 50,
  'british-words': 50,
  'english-contractions': 50,
  'american-contractions': 50,
  'british-contractions': 50,
  'english-upper': 35,
  'american-upper': 35,
  'british-upper': 35,
  'english-abbreviations': 35,
  'american-abbreviations': 35,
  'british-abbreviations': 35,
};

// Arabizi tokens from Ega's presets, few-shots and tests plus common Arabizi words; the lexicon's overlap is ambiguous.
const ARABIZI_SEED = `
ahla ahlan ahl akh akhi akhoya al ala alla allah ana anta ante aw aya aywa aiwa ayez b ba2a bad bade badi
baddi badak badna bardo bas bass be bel bet beit bi bel bukra da dar di dol e eh ehna el eli elli ely enta
enti ento enty ezay fade fadi fi fein feen fil ha habibi habibti hada hadi hal hala halak hay hayda hayde
heik hek hiya hiye hon hone howa huwa illi ilk inni inta inti into intu kam kaman kamen kan kanet keda keef
kif kifak kifik kol kul la lal lama lamma law leh lesh ma mafi mafeesh mabrouk mesh min mish men msh mn nas
nem noor nour rah ras rase sabah sahlan sar salam shu sho tab tamam tayeb w wa wala walla wallah wein wen
wled ya yalla yani yom zay zei zalame shabab sadiqi sadeeqi jama ya3ni add sit hob mot ward
`;

/** The few tar fields this needs: ustar name/prefix, size, and the 512-byte record walk. */
function untar(buf: Buffer): Map<string, Buffer> {
  const files = new Map<string, Buffer>();
  let off = 0;
  while (off + 512 <= buf.length) {
    const header = buf.subarray(off, off + 512);
    if (header.every((b) => b === 0)) break;
    const field = (start: number, len: number): string =>
      header.toString('latin1', start, start + len).replace(/\0.*$/s, '');
    const name = field(345, 155) ? `${field(345, 155)}/${field(0, 100)}` : field(0, 100);
    const size = Number.parseInt(field(124, 12).trim() || '0', 8);
    files.set(name, buf.subarray(off + 512, off + 512 + size));
    off += 512 + Math.ceil(size / 512) * 512;
  }
  return files;
}

async function download(): Promise<Buffer> {
  const cached = await readFile(CACHE).catch(() => null);
  const body = cached ?? Buffer.from(await (await fetch(URL)).arrayBuffer());
  const sum = createHash('sha256').update(body).digest('hex');
  if (sum !== SHA256) throw new Error(`SCOWL download hash ${sum} is not ${SHA256}`);
  if (!cached) await writeFile(CACHE, body);
  return body;
}

async function main(): Promise<void> {
  const files = untar(gunzipSync(await download()));
  const root = `scowl-${VERSION}`;
  const words = new Set<string>();
  for (const [list, max] of Object.entries(LISTS)) {
    for (const [name, data] of files) {
      const m = new RegExp(`^${root}/final/${list}\\.(\\d+)$`).exec(name);
      if (!m || Number(m[1]) > max) continue;
      for (const raw of data.toString('latin1').split('\n')) {
        const w = raw.trim().toLowerCase();
        // Possessives are matched by stripping 's at lookup; one- and two-letter words are neutral anyway.
        if (w.length < 3 || w.endsWith("'s") || !/^\p{L}+(?:'\p{L}+)*$/u.test(w)) continue;
        words.add(w);
      }
    }
  }
  const seed = new Set(ARABIZI_SEED.split(/\s+/).filter((w) => w.length >= 3));
  const ambiguous = [...words].filter((w) => seed.has(w)).sort();
  const common = [...words].filter((w) => !seed.has(w)).sort();
  const notice = files.get(`${root}/Copyright`)?.toString('latin1');
  if (!notice) throw new Error('SCOWL Copyright file is missing from the tarball');

  const header = [
    '# English lexicon for the smart bubble. Generated by scripts/gen-english-lexicon.ts; do not edit.',
    `# Source: SCOWL ${VERSION} (http://wordlist.aspell.net/), ${URL}`,
    '# Lists: words and contractions up to size 50; upper-case words and abbreviations up to size 35.',
    '# Copyright 2000-2018 by Kevin Atkinson, and the authors named in the SCOWL Copyright file.',
    '# License: SCOWL permissive license; full notice in THIRD_PARTY.md.',
    `# ${common.length} common words, then ${ambiguous.length} ambiguous ones (~) that are common Arabizi too.`,
  ];
  const body = [...header, ...common, ...ambiguous.map((w) => `~${w}`)].join('\n');
  await writeFile(OUT, `${body}\n`, 'utf8');
  await mkdir(path.dirname(NOTICE_OUT), { recursive: true });
  await writeFile(NOTICE_OUT, notice.replace(/\r\n/g, '\n').trimEnd() + '\n', 'utf8');
  console.log(
    `wrote ${path.relative(ROOT, OUT)}: ${common.length} common, ${ambiguous.length} ambiguous`,
  );
  console.log(`ambiguous: ${ambiguous.join(' ')}`);
}

await main();
