import fs from 'node:fs/promises';
import path from 'node:path';
import type { RecipeStep } from './replay';

export interface WriteSpecStubOptions {
  sessionDir: string;
  slug: string;
  goalId: string;
  steps: ReadonlyArray<RecipeStep>;
  claim: string;
}

function asString(v: unknown): string | undefined {
  return typeof v === 'string' ? v : undefined;
}

/** Writes <sessionDir>/repro/<slug>.flow.spec.ts replaying the recipe, for a human to promote or drop. */
export async function writeSpecStub(opts: WriteSpecStubOptions): Promise<string> {
  const lines: string[] = [];
  // explore.* markers stay out of tests/e2e/flows/coverage.ts until a human promotes the stub.
  lines.push(`/* coverage: explore.${opts.goalId}.${opts.slug} */`);
  lines.push(`import { test } from '@playwright/test';`);
  lines.push('');
  lines.push(`// Auto-generated by tests/explore/. Goal: ${opts.goalId}.`);
  lines.push(`// Claim: ${opts.claim}`);
  lines.push('');
  const safeClaim = opts.claim.replace(/'/g, "\\'");
  lines.push(`test('${opts.goalId}: ${safeClaim}', async ({ page }) => {`);

  for (const s of opts.steps) {
    switch (s.tool) {
      case 'browser_navigate': {
        const url = asString(s.input['url']);
        if (url !== undefined) lines.push(`  await page.goto(${JSON.stringify(url)});`);
        break;
      }
      case 'browser_click': {
        const sel = asString(s.input['selector']);
        const role = asString(s.input['role']);
        const name = asString(s.input['name']);
        if (sel !== undefined) {
          lines.push(`  await page.click(${JSON.stringify(sel)});`);
        } else if (role !== undefined) {
          if (name === undefined) {
            lines.push(`  await page.getByRole(${JSON.stringify(role)}).click();`);
          } else {
            lines.push(
              `  await page.getByRole(${JSON.stringify(role)}, { name: ${JSON.stringify(name)} }).click();`,
            );
          }
        }
        break;
      }
      case 'browser_type': {
        const sel = asString(s.input['selector']);
        const val = asString(s.input['value']);
        if (sel !== undefined && val !== undefined) {
          lines.push(`  await page.fill(${JSON.stringify(sel)}, ${JSON.stringify(val)});`);
        }
        break;
      }
      case 'browser_wait': {
        const sel = asString(s.input['selector']);
        if (sel !== undefined) {
          lines.push(`  await page.waitForSelector(${JSON.stringify(sel)});`);
        } else if (typeof s.input['ms'] === 'number') {
          lines.push(`  await page.waitForTimeout(${s.input['ms']});`);
        }
        break;
      }
      case 'assert': {
        const claim = asString(s.input['claim']) ?? '';
        const predicate = asString(s.input['predicate']) ?? '';
        lines.push(`  // assert: ${claim}`);
        if (predicate.length > 0) {
          lines.push(
            `  // predicate evaluated in page: ${predicate.slice(0, 120).replace(/\n/g, ' ')}`,
          );
        }
        break;
      }
      default:
        lines.push(`  // (skipped recipe step: ${s.tool})`);
    }
  }
  lines.push(`});`);
  lines.push('');

  await fs.mkdir(path.join(opts.sessionDir, 'repro'), { recursive: true });
  const file = path.join(opts.sessionDir, 'repro', `${opts.slug}.flow.spec.ts`);
  await fs.writeFile(file, lines.join('\n'));
  return file;
}
